### ISSUE TITLE
Update Duckdb Amalgation source code to the latest current version (0.7.0)

### ISSUE THREAD

**Issue by mindreframer** [AlexR2D2/duckdbex#5]
Currently we do not have the latest version of DuckDB in the codebase. 

It would be also great to have a Makefile or a bash script to keep the update process reproducible and documented.

For example in Exqlite there is a small bash script for this: 
- https://github.com/elixir-sqlite/exqlite/blob/main/bin/download_sqlite.sh

Having the Duckdb version exposed as something accessible in Elixir would help to decide which features / bugs / etc are available to be used.

**Comment by AlexR2D2** [comment]
Now the `Duckdbex.library_version()` returns the correct library version. It was fixed in DuckDB source code.

Also added the `Duckdbex.storage_format_version()`. It returns the version number of the database storage format what this library supports. As I understand it, different versions of libraries can support the same storage format.

There is also the Duckdbex.library_version/1 to get library versions what support the storage format:

```Elixir
iex > Duckdbex.library_version
"v0.7.1"
iex > Duckdbex.storage_format_version
43
iex > Duckdbex.library_version 39
"v0.6.0 or v0.6.1"
```

Added the bash [script](https://github.com/AlexR2D2/duckdbex/blob/main/bin/download_duckdb.sh) to update DuckDB source code.

**Comment by mindreframer** [comment]
@AlexR2D2 awesome! Thank you, this looks great. It's slowly getting great!
